### ISSUE TITLE
Can I apply your tool for predict plant protein function ?

### ISSUE THREAD

**Issue by anani-a-missinou** [cansyl/DEEPred#3]
I am a Ph.D. student metabolomic/specialized plant metabolic responses to pathogens.

Your deep learning approach applied to the protein function prediction is very innovative. I'd like to apply it to my plant data to predict the biosynthetic gene cluster.

Does DEEPred work with plants (Brassica spp) data?

IMPORTANT: These plants contain approximately 6 copies of each gene resulting from duplication and therefore a large question of neofunctionalization and subfunctionalization. This is without taking into account the tandem duplication events on the same chromosome.

Thank you for your reply

**Comment by tuncadogan** [comment]
Thank you for your interest in our tool. Our method is based on the sequence similarities between the query sequence and the database sequences (our training dataset sequences), which have known/documented functions. What our method needs as input is the discrete amino acid sequences of proteins.

Our tool was developed within a global approach, and there are also sequences from different plant species in our training set. However, if these multiple copies have diverged to obtain completely different functions (that cannot be found in other plant species), it will be impossible for DEEPred to predict these new functions. Please let us know if you have further questions.
